# Lab 4

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/lweber89/geog510-test/blob/main/labs/geog510_lab_04_lweber89.ipynb)

## Exercise 1: Variable Assignment and Basic Operations

Create variables to store the following geospatial data:

- The latitude and longitude of New York City: 40.7128, -74.0060.
- The population of New York City: 8,336,817.
- The area of New York City in square kilometers: 783.8.

Perform the following tasks:

1. Calculate and print the population density of New York City (population per square kilometer).
2. Print the coordinates in the format "Latitude: [latitude], Longitude: [longitude]".

In [80]:
#Assign Initial Variables

geocoord_NYC = (40.7128, -74.0060)  #Geocoords (lat/long) of New York City, USA
pop_NYC = 8336817  #Population of New York City, USA
area_NYC = 783.8 #Area of New York City, USA in sq km

#Output pop density and geocoords

print (f"NYC Population Density: {(pop_NYC/area_NYC):.2f} people/sq km")

print(f"NYC Geocoords: Latitude: {geocoord_NYC[0]:.4f} Longitude: {geocoord_NYC[1]:.4f}")


NYC Population Density: 10636.41 people/sq km
NYC Geocoords: Latitude: 40.7128 Longitude: -74.0060


## Exercise 2: Working with Strings

Create a string variable to store the name of a city, such as "San Francisco". Perform the following operations:

1. Convert the string to lowercase and print the result.
2. Convert the string to uppercase and print the result.
3. Replace "San" with "Los" in the city name and print the new string.

In [81]:
#Assign Initial Variable

city_name = "Saint Louis"

#Perform string operations and print

city_name_lower = city_name.lower()
print (city_name_lower)

city_name_upper = city_name.upper()
print (city_name_upper)

city_name_replace = city_name.replace("Saint", "Los")
print(city_name_replace)

saint louis
SAINT LOUIS
Los Louis


## Exercise 3: Using Lists

Create a list of tuples, where each tuple contains the name of a city and its corresponding latitude and longitude:

- New York City: (40.7128, -74.0060)
- Los Angeles: (34.0522, -118.2437)
- Chicago: (41.8781, -87.6298)

Perform the following tasks:

1. Add a new city (e.g., Miami: (25.7617, -80.1918)) to the list.
2. Print the entire list of cities.
3. Slice the list to print only the first two cities.

In [82]:
#Create initial list of tuples (city, lat, lon)
cities = [("New York City", 40.7128, -74.0060), ("Los Angeles", 34.0522, -118.2437), ("Chicago", 41.8781, -87.6298)]

#Append to list and print

cities.append(("Miami", 25.7617, -80.1918))
print(cities)

#Print out only first 2 cities

print(cities[:2])

[('New York City', 40.7128, -74.006), ('Los Angeles', 34.0522, -118.2437), ('Chicago', 41.8781, -87.6298), ('Miami', 25.7617, -80.1918)]
[('New York City', 40.7128, -74.006), ('Los Angeles', 34.0522, -118.2437)]


## Exercise 4: Using Tuples

Create a tuple to store the coordinates (latitude, longitude) of the Eiffel Tower: (48.8584, 2.2945). Perform the following tasks:

1. Access and print the latitude and longitude values from the tuple.
2. Try to change the latitude value to 48.8585. What happens? Explain why.

In [83]:
#Assign Initial Value

geocoord_EiffelTwr = (48.8584, 2.2945)

print(f"Eiffel Tower Geocoords: Latitude: {geocoord_EiffelTwr[0]} Longitude: {geocoord_EiffelTwr[1]}")


#Attempt to change value of geocoord_EiffelTwr latitude element.  Note: error is expected.

#geocoord_EiffelTwr[0] = 48.8585

print("geocoord_EiffelTwr is a tuple data structure.  Tuples are immutable and once assigned individual elements cannot be changed.")

Eiffel Tower Geocoords: Latitude: 48.8584 Longitude: 2.2945
geocoord_EiffelTwr is a tuple data structure.  Tuples are immutable and once assigned individual elements cannot be changed.


## Exercise 5: Working with Sets

Create a set of countries you have visited, such as {"USA", "France", "Germany"}. Perform the following tasks:

1. Add a new country to the set.
2. Try to add the same country again. What happens?
3. Print the updated set.

In [84]:
#Assigin initial values to set

countries_visited = {"USA", "Canada", "Germany", "Saudi Arabia", "UK"}

#Output original set
print(countries_visited)

#Add new country to the set
countries_visited.add("Netherlands")

#Output updated set
print(countries_visited)

#Attempt to add same country again
countries_visited.add("Netherlands")  #This line attempts to add a duplicate value to the set.  While not an error, this line will be ignored.

print (countries_visited)

{'UK', 'Saudi Arabia', 'Canada', 'USA', 'Germany'}
{'UK', 'Saudi Arabia', 'Netherlands', 'Canada', 'USA', 'Germany'}
{'UK', 'Saudi Arabia', 'Netherlands', 'Canada', 'USA', 'Germany'}


## Exercise 6: Working with Dictionaries

Create a dictionary to store information about a specific geospatial feature, such as a river:

- Name: "Amazon River"
- Length: 6400 km
- Countries: ["Brazil", "Peru", "Colombia"]

Perform the following tasks:

1. Add a new key-value pair to the dictionary to store the river's average discharge (e.g., 209,000 m³/s).
2. Update the length of the river to 6992 km.
3. Print the dictionary.

In [85]:
#Initialize dictionary and print

river = {
    "name": "Amazon River",
    "length": 6400,
    "countries": ["Brazil", "Peru", "Colombia"]
}

print(river)

#Update dictionary and print

river["avg_discharge"] = 209000
river["length"] = 6992

print(river)

{'name': 'Amazon River', 'length': 6400, 'countries': ['Brazil', 'Peru', 'Colombia']}
{'name': 'Amazon River', 'length': 6992, 'countries': ['Brazil', 'Peru', 'Colombia'], 'avg_discharge': 209000}


## Exercise 7: Nested Data Structures

Create a dictionary to represent a city that contains the city's name, population, and coordinates (latitude, longitude):

- Name: "Tokyo"
- Population: 13,515,271
- Coordinates: (35.6895, 139.6917)

Perform the following tasks:

1. Access and print the population of the city.
2. Access and print the city's latitude.
3. Update the population to 14,000,000 and print the updated dictionary.

In [86]:
#Initialize dictionary and print

city_info = {
    "name": "Tokyo",
    "pop": 13515271,
    "coords": (35.6895, 139.6917)
}

print(city_info)

#Print pop of city

print(city_info["pop"])

#Print latitude of city

print(city_info["coords"][0])

#Update pop and print updated dictionary

city_info["pop"] = 14000000

print(city_info)



{'name': 'Tokyo', 'pop': 13515271, 'coords': (35.6895, 139.6917)}
13515271
35.6895
{'name': 'Tokyo', 'pop': 14000000, 'coords': (35.6895, 139.6917)}


## Exercise 8: List Operations

Given the list of cities from Exercise 3, perform the following operations:

1. Sort the list of cities alphabetically by name.
2. Create a new list that contains only the city names.
3. Remove the last city from the original list and print the updated list.

In [87]:
#Sort and print cities in alphabetical order

cities.sort()
print (cities)

#Create new list with only city names
only_names = [cities[0][0], cities[1][0], cities[2][0], cities[3][0]]
print(only_names)

#Remove last city from original list and print

del only_names[-1]
print(only_names)



[('Chicago', 41.8781, -87.6298), ('Los Angeles', 34.0522, -118.2437), ('Miami', 25.7617, -80.1918), ('New York City', 40.7128, -74.006)]
['Chicago', 'Los Angeles', 'Miami', 'New York City']
['Chicago', 'Los Angeles', 'Miami']


## Exercise 9: Dictionary Operations

Using the dictionary from Exercise 6, perform the following tasks:

1. Check if the key "Length" exists in the dictionary.
2. Print all the keys in the dictionary.
3. Print all the values in the dictionary.

In [88]:
#Check if key "length" exists in dictionary

print("length" in river)

#Print all the keys in the dictionary
print(river.keys())

#Print all the values in the dictionary
print(river.values())

True
dict_keys(['name', 'length', 'countries', 'avg_discharge'])
dict_values(['Amazon River', 6992, ['Brazil', 'Peru', 'Colombia'], 209000])


## Exercise 10: Practical Application

Imagine you have a list of tuples, each representing a location with its name, latitude, and longitude:

In [89]:
locations = [
    ("Mount Everest", 27.9881, 86.9250),
    ("K2", 35.8808, 76.5155),
    ("Kangchenjunga", 27.7025, 88.1475),
]

Perform the following tasks:

1. Create a new list that contains only the names of the locations.
2. Create a dictionary where the keys are location names and the values are tuples of their coordinates.
3. Print the latitude of "K2" using the dictionary.

In [90]:
#Create and print list that contains only location names
location_names = [locations[0][0], locations[1][0], locations[2][0]]
print(location_names)

#Dictionary built from list, print to verify creation 

locations_dictionary = {"Mount Everest": (27.9881, 86.9250),
                        "K2": (35.8808, 76.5155),
                        "Kangchenjunga": (27.7025, 88.1475)}

print(locations_dictionary)

#Print latitude of K2 via the dictionary

print(locations_dictionary["K2"][0])


['Mount Everest', 'K2', 'Kangchenjunga']
{'Mount Everest': (27.9881, 86.925), 'K2': (35.8808, 76.5155), 'Kangchenjunga': (27.7025, 88.1475)}
35.8808


## Exercise 11: Manipulating Geographic Location Strings

- Create a string that represents the name of a geographic feature (e.g., `"Amazon River"`).
- Convert the string to lowercase and then to uppercase.
- Concatenate the string with the name of the country (e.g., `"Brazil"`) to create a full location name.
- Repeat the string three times, separating each repetition with a dash (`-`).

In [91]:
#Create and print string

geog_feature = "Amazon River"
print(geog_feature)

#Convert to lowercase and print

geog_feature_lower = geog_feature.lower()
print(geog_feature_lower)

#Convert to uppercase and print
geog_feature_upper = geog_feature.upper()
print(geog_feature_upper)

#Concatenate and print
geog_feature_full = geog_feature + ", Brazil"
print(geog_feature_full)

#Repeat string with "-" between

output = " - ".join([geog_feature_full] * 3)
print(output)


Amazon River
amazon river
AMAZON RIVER
Amazon River, Brazil
Amazon River, Brazil - Amazon River, Brazil - Amazon River, Brazil


## Exercise 12: Extracting and Formatting Coordinates

- Given a string with the format `"latitude, longitude"` (e.g., `"40.7128N, 74.0060W"`), extract the numeric values of latitude and longitude.
- Convert these values to floats and remove the directional indicators (`N`, `S`, `E`, `W`).
- Format the coordinates into a `POINT` WKT string (e.g., `"POINT(-74.0060 40.7128)"`).

In [92]:
#Initialize variable

geocoord_string = "40.7128N, 74.0060W"

#Initial unpack based on seperator
parts = geocoord_string.split(",")

#Strip unpacked components
lat_str = parts[0].strip()
lon_str = parts[1].strip()

print("String Unpacked")
print (lat_str)
print (lon_str)

#Remove N/W and convert to floats

print("\nStrip and Convert to floats")
lat_flt = float(lat_str[:-1]) 
lon_flt = float(lon_str[:-1]) 

print(lat_flt)
print(lon_flt)

#Create WKT representation

wkt_pt = f"POINT({lon_flt} {lat_flt})"
print("\n")
print(f"WKT Point:  {wkt_pt}")


String Unpacked
40.7128N
74.0060W

Strip and Convert to floats
40.7128
74.006


WKT Point:  POINT(74.006 40.7128)


## Exercise 13: Building Dynamic SQL Queries

- Given a table name and a condition, dynamically build an SQL query string.
- Example: If `table_name = "cities"` and `condition = "population > 1000000"`, the query should be `"SELECT * FROM cities WHERE population > 1000000;"`.
- Add additional conditions dynamically, like `AND` clauses.

In [93]:
#Assign table_name and base query

table_name = "cities"
base_query = "SELECT * FROM "

#Construct lists of conditions

conditions_1 = ["population > 1000000"]

conditions_2 = ["population > 1000000", "coastal = TRUE"]

conditions_3 = ["population > 1000000", "coastal = TRUE", "avg_rainfall > 40"]

#Build dynamic queries

query_1 = base_query + table_name + " WHERE " + " AND ".join(conditions_1) +";"
print(query_1)

query_2 = base_query + table_name + " WHERE " + " AND ".join(conditions_2) +";"
print(query_2)

query_3 = base_query + table_name + " WHERE " + " AND ".join(conditions_3) +";"
print(query_3)

SELECT * FROM cities WHERE population > 1000000;
SELECT * FROM cities WHERE population > 1000000 AND coastal = TRUE;
SELECT * FROM cities WHERE population > 1000000 AND coastal = TRUE AND avg_rainfall > 40;


## Exercise 14: String Normalization and Cleaning

- Given a list of city names with inconsistent formatting (e.g., `[" new york ", "Los ANGELES", "   CHICAGO"]`), normalize the names by:
  - Stripping any leading or trailing whitespace.
  - Converting them to title case (e.g., `"New York"`, `"Los Angeles"`, `"Chicago"`).
- Ensure that the output is a clean list of city names.

In [94]:
#Initialize list

city_list = [" new york", "Los ANGELES", " CHICAGO"]

#Create empty list to hold cleaned values

city_list_clean = []

#Loop through city list and format to title case and stip whitespace

for city in city_list:
    temp = city.title()
    temp = temp.strip()
    city_list_clean.append(temp)

#Print result
 
print (city_list_clean)

['New York', 'Los Angeles', 'Chicago']


## Exercise 15: Parsing and Extracting Address Information

- Given a string in the format `"Street, City, Country"` (e.g., `"123 Main St, Springfield, USA"`), write a function that parses the string into a dictionary with keys `street`, `city`, and `country`.
- The function should return a dictionary like `{"street": "123 Main St", "city": "Springfield", "country": "USA"}`.

In [95]:
#Define function that takes in a string address and returns a dictionary

def address_dictionary_builder (address):

#Initialize empty dictionary

    address_dictionary = {
        "street": "",
        "city": "",
        "country": "",
        }

    #Split address on ","
    address_parts = address.split(",")

    #Assign address components to dictionary entries

    address_dictionary["street"] = address_parts[0].strip()
    address_dictionary["city"] = address_parts[1].strip()
    address_dictionary["country"] = address_parts[2].strip()
    
    #return completed dictionary
    
    return address_dictionary


In [96]:
#Example usage

address = "123 Main St, Springfield, USA"
d = address_dictionary_builder(address)
print(d)

{'street': '123 Main St', 'city': 'Springfield', 'country': 'USA'}


## Exercise 16: Using For Loops to Process Coordinate Lists

- Create a list of tuples representing coordinates (latitude, longitude).
- Write a `for` loop that prints each coordinate and indicates whether it is in the Northern or Southern Hemisphere based on the latitude.

In [97]:
#Create list of coordinates

coordinates = [
    (34.0522, -118.2437),  # Los Angeles
    (-33.8688, 151.2093),  # Sydney
    (40.7128, -74.0060),   # New York
    (-23.5505, -46.6333),  # São Paulo
    (0.0000, 32.4467),     # Entebbe (Equator)
    (51.5074, -0.1278),    # London
    (-34.6037, -58.3816),  # Buenos Aires
    (35.6895, 139.6917),   # Tokyo
    (-1.2921, 36.8219),    # Nairobi
    (48.8566, 2.3522),     # Paris
    (38.6270, -90.1994)    # St. Louis
]

#Loop through coordinates list and check for Northern or Southern Hemisphere - output result

for lat, lon in coordinates:
    if lat > 0:
        print(f"The coordinate {lat:.4f}, {lon:.4f} is in the Northern Hemisphere.")
    elif lat < 0:
        print(f"The coordinate {lat:.4f}, {lon:.4f} is in the Southern Hemisphere.")
    else:
        print(f"The coordinate {lat:.4f}, {lon:.4f} is on the equator!")

The coordinate 34.0522, -118.2437 is in the Northern Hemisphere.
The coordinate -33.8688, 151.2093 is in the Southern Hemisphere.
The coordinate 40.7128, -74.0060 is in the Northern Hemisphere.
The coordinate -23.5505, -46.6333 is in the Southern Hemisphere.
The coordinate 0.0000, 32.4467 is on the equator!
The coordinate 51.5074, -0.1278 is in the Northern Hemisphere.
The coordinate -34.6037, -58.3816 is in the Southern Hemisphere.
The coordinate 35.6895, 139.6917 is in the Northern Hemisphere.
The coordinate -1.2921, 36.8219 is in the Southern Hemisphere.
The coordinate 48.8566, 2.3522 is in the Northern Hemisphere.
The coordinate 38.6270, -90.1994 is in the Northern Hemisphere.


## Exercise 17: While Loops for Iterative Processing

- Create a list of coordinates (latitude, longitude).
- Write a `while` loop that continues to print each coordinate until it encounters a coordinate with a negative latitude.
- Stop the loop once this condition is met.

In [98]:
#Create list of coordinates
coordinates = [
    (45.5231, -122.6765), # Portland
    (52.3676, 4.9041),   # Amsterdam
    (39.9042, 116.4074),  # Beijing
    (38.6270, -90.1994),  # St. Louis
    (-1.2921, 36.8219),   # Nairobi
    (40.7128, -74.0060),  # New York
    (-33.8688, 151.2093)  # Sydney
]

#Contruct while loop to iterate through coordinates and output until negative latitude is encountered

counter = 0

while counter < len(coordinates):
    lat, lon = coordinates[counter] #extract lat/lon from coord tuple

    if lat >= 0:
        print(f"{lat:.4f}, {lon:.4f}")
    else:
        break

    counter += 1

45.5231, -122.6765
52.3676, 4.9041
39.9042, 116.4074
38.6270, -90.1994


## Exercise 18: Conditional Logic in Loops

- Create a list of coordinates and use a `for` loop to iterate over them.
- Use an `if-elif-else` statement inside the loop to classify each coordinate based on its longitude:
  - Print `"Eastern Hemisphere"` if the longitude is greater than 0.
  - Print `"Western Hemisphere"` if the longitude is less than 0.

In [99]:
#Create list of coordinates

coordinates = [
    (90.0000, 0.0000),    # North Pole
    (-34.6037, -58.3816), # Buenos Aires
    (0.0000, 0.0000),     # Null Island
    (35.6895, 139.6917),  # Tokyo
    (51.4779, 0.0000),    # Greenwich
    (40.7128, -74.0060),  # New York
    (-90.0000, 0.0000),   # South Pole
    (48.8566, 2.3522),    # Paris
    (38.6270, -90.1994),  # St. Louis
    (-33.8688, 151.2093), # Sydney
    (24.3451, 0.0000),    # Algeria (Sahara)
    (55.7558, 37.6173),   # Moscow
    (-23.5505, -46.6333), # São Paulo
    (30.0444, 31.2357),   # Cairo
    (-1.2921, 36.8219),   # Nairobi
    (19.4326, -99.1332),  # Mexico City
    (64.1466, -21.9426),  # Reykjavik
    (-22.9068, -43.1729), # Rio de Janeiro
    (34.0522, -118.2437), # Los Angeles
    (1.2921, 103.8519)    # Singapore
]

#Extract coordinates and check for Eastern Hemisphere, Western Hemisphere, Prime Meridian or Polar location

for lat, lon in coordinates:
    if abs(lat) == 90:
        print("You are at a pole!")
    elif lon > 0:
        print("Eastern Hemisphere")
    elif lon < 0:
        print("Western Hemisphere")
    else:
        print("You are on the prime meridian!")

You are at a pole!
Western Hemisphere
You are on the prime meridian!
Eastern Hemisphere
You are on the prime meridian!
Western Hemisphere
You are at a pole!
Eastern Hemisphere
Western Hemisphere
Eastern Hemisphere
You are on the prime meridian!
Eastern Hemisphere
Western Hemisphere
Eastern Hemisphere
Eastern Hemisphere
Western Hemisphere
Western Hemisphere
Western Hemisphere
Western Hemisphere
Eastern Hemisphere


## Exercise 19: Filtering Data with Combined Loops and Conditionals

- Given a list of coordinates, filter out and store only those located in the Southern Hemisphere (latitude < 0).
- Count the number of coordinates that meet this condition and print the result.

In [100]:
#Constuct list of coordinates

coordinates = [
    (90.0000, 0.0000),    # North Pole
    (-34.6037, -58.3816), # Buenos Aires
    (0.0000, 0.0000),     # Null Island
    (35.6895, 139.6917),  # Tokyo
    (51.4779, 0.0000),    # Greenwich
    (40.7128, -74.0060),  # New York
    (-90.0000, 0.0000),   # South Pole
    (48.8566, 2.3522),    # Paris
    (38.6270, -90.1994),  # St. Louis
    (-33.8688, 151.2093), # Sydney
    (24.3451, 0.0000),    # Algeria (Sahara)
    (55.7558, 37.6173),   # Moscow
    (-23.5505, -46.6333), # São Paulo
    (30.0444, 31.2357),   # Cairo
    (-1.2921, 36.8219),   # Nairobi
    (19.4326, -99.1332),  # Mexico City
    (64.1466, -21.9426),  # Reykjavik
    (-22.9068, -43.1729), # Rio de Janeiro
    (34.0522, -118.2437), # Los Angeles
    (1.2921, 103.8519),   # Singapore
    (52.5200, 13.4050),   # Berlin
    (-26.2041, 28.0473),  # Johannesburg
    (39.9042, 116.4074),  # Beijing
    (-37.8136, 144.9631), # Melbourne
    (25.2048, 55.2708),   # Dubai
    (-12.0464, -77.0428), # Lima
    (59.3293, 18.0686),   # Stockholm
    (22.3193, 114.1694),  # Hong Kong
    (45.4215, -75.6972),  # Ottawa
    (-36.8485, 174.7633), # Auckland
    (13.7563, 100.5018),  # Bangkok
    (51.5074, -0.1278),   # London
    (28.6139, 77.2090),   # New Delhi
    (-34.9285, 138.6007), # Adelaide
    (53.3498, -6.2603),   # Dublin
    (37.9838, 23.7275),   # Athens
    (41.9028, 12.4964),   # Rome
    (60.1699, 24.9384),   # Helsinki
    (31.2304, 121.4737),  # Shanghai
    (-15.7975, -47.8919), # Brasilia
    (43.6532, -79.3832),  # Toronto
    (33.4484, -112.0740), # Phoenix
    (1.3521, 103.8198),   # Singapore (Central)
    (35.6762, 139.6503),  # Tokyo (West)
    (-41.2865, 174.7762), # Wellington
    (59.9139, 10.7522),   # Oslo
    (41.3851, 2.1734),    # Barcelona
    (-33.9249, 18.4241),  # Cape Town
    (14.5995, 120.9842),  # Manila
    (21.3069, -157.8583)  # Honolulu
]

s_hemi_coords = []

for lat, lon in coordinates:
    if lat < 0:
        s_hemi_coords.append((lat, lon))

orig_coord_len = len(coordinates)
s_hemi_coord_len = len(s_hemi_coords)

print(f"Out of {orig_coord_len} coordinates in the original list, {s_hemi_coord_len} are in the Southern Hemisphere")

print("\nFiltered Southern Hemisphere Coordinates:")
for coord in s_hemi_coords:
    print(coord)


Out of 50 coordinates in the original list, 14 are in the Southern Hemisphere

Filtered Southern Hemisphere Coordinates:
(-34.6037, -58.3816)
(-90.0, 0.0)
(-33.8688, 151.2093)
(-23.5505, -46.6333)
(-1.2921, 36.8219)
(-22.9068, -43.1729)
(-26.2041, 28.0473)
(-37.8136, 144.9631)
(-12.0464, -77.0428)
(-36.8485, 174.7633)
(-34.9285, 138.6007)
(-15.7975, -47.8919)
(-41.2865, 174.7762)
(-33.9249, 18.4241)


## Exercise 20: Generating and Analyzing Random Coordinates

- Write a program that generates random coordinates (latitude between [-90, 90] degrees and longitude between [-180, 180] degrees).
- Use a `while` loop to keep generating coordinates until a pair with both latitude and longitude greater than 50 is generated.
- Print each generated coordinate and the final coordinate that meets the condition.

In [101]:
import random

while True:
    random_lat = random.uniform(-90, 90)  #create a random latitude
    random_lon = random.uniform(-180, 180) #create a random longitude

    #check if lat and lon are > 50, print output and break once both are > 50

    if random_lat <= 50 and random_lon <= 50:
        print(f"Coord: {random_lat:.4f}, {random_lon:.4f}")

    if random_lat > 50 and random_lon > 50:
        print(f"Final Coord: {random_lat:.4f}, {random_lon:.4f}")
        break


Coord: -55.4524, -175.3556
Coord: -20.1354, -147.0178
Final Coord: 72.1467, 144.1328


## Submission Requirements

Complete the exercises above and and upload the notebook to your GitHub repository. Make sure the notebook has a Colab badge at the top so that it can be easily opened in Google Colab. Submit the URL of the notebook to Canvas.